name: binder_env
channels:
  - defaults
dependencies:
  - python=2.7
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - xlrd 
  - beautifulsoup4
  - urllib3
  - requests
  - nltk
  - scikit-learn=0.19.1
